# Generated by Django 4.1.3 on 2023-08-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_AUTH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('sub_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'draft'), ('published', 'published')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main_AUTH.user_profile')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ('-id',),
            },
        ),
    ]
